# File naming and format
save_file_name: "2D_omega"
save_file_extension: ".svg"

# File handling settings
is_multi_files: false
target_folder_multi_files: "./csv/"
plots_folder: "plots"

# Analysis settings
extremum_of: "rho"
based_on_guiding_center: true
calculate_integral: true
calculate_traditional_magneticMoment: false
show_extremums_peaks: false
show_amplitude_analysis: true

# Plot settings
SHARE_X_AXIS: true

# Simulation parameters
simulation_time: 100
method: "Feagin14 Method"

# Simulation parameters dictionary (if needed)
simulation_parameters:
  time: 100
  method: "Feagin14 Method"
